version: 2.1

executors:
  ci-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim
    working_directory: ~/Frogvall/aspnetcore-exceptionhandler

jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      - run: dotnet restore
      - run: cd test/aspnetcore-exceptionhandler-test
      - run: dotnet test --test-adapter-path:. --logger:"xunit;LogFilePath=./../../testresults/out.xml"
      - run: cd ../..
      - run: dotnet pack src/aspnetcore-exceptionhandler/aspnetcore-exceptionhandler.csproj -c release -o ./package/base
      - run: dotnet pack src/aspnetcore-exceptionhandler-awsxray/aspnetcore-exceptionhandler-awsxray.csproj -c release -o ./package/awsxray
      - run: dotnet pack src/aspnetcore-exceptionhandler-modelvalidation/aspnetcore-exceptionhandler-modelvalidation.csproj -c release -o ./package/modelvalidation
      - run: dotnet pack src/aspnetcore-exceptionhandler-newtonsoftjson/aspnetcore-exceptionhandler-newtonsoftjson.csproj -c release -o ./package/newtonsoftjson
      - run: dotnet pack src/aspnetcore-exceptionhandler-swagger/aspnetcore-exceptionhandler-swagger.csproj -c release -o ./package/swagger
      - persist_to_workspace:
          root: ~/Frogvall/aspnetcore-exceptionhandler
          paths:
            - package
      - store_test_results:
          path: ./testresults
  deploy-base:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: ~/Frogvall/aspnetcore-exceptionhandler
      - run: dotnet nuget push package/base/*.nupkg -k $Nuget_Api_Key -s https://api.nuget.org/v3/index.json
  deploy-awsxray:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: ~/Frogvall/aspnetcore-exceptionhandler
      - run: dotnet nuget push package/awsxray/*.nupkg -k $Nuget_Api_Key -s https://api.nuget.org/v3/index.json
  deploy-modelvalidation:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: ~/Frogvall/aspnetcore-exceptionhandler
      - run: dotnet nuget push package/modelvalidation/*.nupkg -k $Nuget_Api_Key -s https://api.nuget.org/v3/index.json
  deploy-newtonsoftjson:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: ~/Frogvall/aspnetcore-exceptionhandler
      - run: dotnet nuget push package/newtonsoftjson/*.nupkg -k $Nuget_Api_Key -s https://api.nuget.org/v3/index.json
  deploy-swagger:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: ~/Frogvall/aspnetcore-exceptionhandler
      - run: dotnet nuget push package/swagger/*.nupkg -k $Nuget_Api_Key -s https://api.nuget.org/v3/index.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:  # required since `deploy-*` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy-base:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-awsxray:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
                - /^awsxray-v.*/
            branches:
              ignore: /.*/
      - deploy-modelvalidation:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
                - /^modelvalidation-v.*/
            branches:
              ignore: /.*/
      - deploy-newtonsoftjson:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
                - /^newtonsoftjson-v.*/
            branches:
              ignore: /.*/
      - deploy-swagger:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
                - /^swagger-v.*/
            branches:
              ignore: /.*/
