version: 2.1

executors:
  ci-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: ~/Frogvall/aspnetcore-exceptionhandler

jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      - run: dotnet restore
      - run: cd test/aspnetcore-exceptionhandler-test
      - run: dotnet test --test-adapter-path:. --logger:"xunit;LogFilePath=./../../testresults/out.xml"
      - run: cd ../..
      - run: dotnet pack src/aspnetcore-exceptionhandler/aspnetcore-exceptionhandler.csproj -c release -o ./../../package
      - run: dotnet pack src/aspnetcore-exceptionhandler-awsxray/aspnetcore-exceptionhandler-awsxray.csproj -c release -o ./../../package
      - run: dotnet pack src/aspnetcore-exceptionhandler-modelvalidation/aspnetcore-exceptionhandler-modelvalidation.csproj -c release -o ./../../package
      - run: dotnet pack src/aspnetcore-exceptionhandler-swagger/aspnetcore-exceptionhandler-swagger.csproj -c release -o ./../../package
      - persist_to_workspace:
          root: ~/Frogvall/aspnetcore-exceptionhandler
          paths:
            - package
      - store_test_results:
          path: ./testresults
  deploy:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: ~/Frogvall/aspnetcore-exceptionhandler
      - run: dotnet nuget push package/*.nupkg -k $Nuget_Api_Key

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master