<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Frogvall.AspNetCore.ExceptionHandling.Test</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="XunitXml.TestLogger" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\aspnetcore-exceptionhandler-awsxray\aspnetcore-exceptionhandler-awsxray.csproj" />
    <ProjectReference Include="..\..\src\aspnetcore-exceptionhandler-modelvalidation\aspnetcore-exceptionhandler-modelvalidation.csproj" />
    <ProjectReference Include="..\..\src\aspnetcore-exceptionhandler-swagger\aspnetcore-exceptionhandler-swagger.csproj" />
    <ProjectReference Include="..\..\src\aspnetcore-exceptionhandler-newtonsoftjson\aspnetcore-exceptionhandler-newtonsoftjson.csproj" />
    <ProjectReference Include="..\..\src\aspnetcore-exceptionhandler\aspnetcore-exceptionhandler.csproj" />
    <ProjectReference Include="..\..\test\aspnet-core-exceptionhandler-test-mapping-profiles\aspnet-core-exceptionhandler-test-mapping-profiles.csproj" />
  </ItemGroup>

</Project>
